export const CERTIFICATION = {
  id: 'ml_certification',
  title: 'Certified ML Practitioner Exam',
  subtitle: '50 questions · 60 minutes · Pass: 70% · Job Guarantee: 89%+',
  passingScore: 70,
  jobGuaranteeScore: 89,
  icon: '🏆',
  questions: [
    { q: 'Which best defines Machine Learning?', options: ['Writing rules for every scenario', 'Computers learning patterns from data', 'A database query language', 'Statistical sampling'], correct: 1 },
    { q: 'Which is NOT a type of Machine Learning?', options: ['Supervised', 'Unsupervised', 'Reinforcement', 'Deterministic'], correct: 3 },
    { q: "What does a 'label' represent in supervised learning?", options: ['An input feature', 'The correct output/answer for a training example', 'A data cleaning step', 'A type of neural network layer'], correct: 1 },
    { q: 'Overfitting occurs when:', options: ['The model is too simple', 'The model memorises training data and fails on new data', 'The dataset is too small', 'The learning rate is too low'], correct: 1 },
    { q: 'What does the train/test split prevent?', options: ['Slow training', 'Measuring performance on data the model has already seen', 'Feature correlation', 'Gradient explosion'], correct: 1 },
    { q: 'Mean Squared Error (MSE) is used for:', options: ['Classification problems', 'Regression problems — measuring average squared prediction error', 'Clustering quality', 'Dimensionality reduction'], correct: 1 },
    { q: 'Gradient descent minimises the:', options: ['Training dataset size', 'Loss function by adjusting model weights iteratively', 'Number of features', 'Prediction speed'], correct: 1 },
    { q: 'The sigmoid function maps any number to:', options: ['0 to infinity', '−1 to 1', '0 to 1', '−∞ to ∞'], correct: 2 },
    { q: 'Decision Trees split data using:', options: ['Random guesses', 'Information gain — choosing the feature that reduces impurity most', 'Gradient descent', 'Euclidean distance'], correct: 1 },
    { q: "KNN is called a 'lazy learner' because:", options: ['It trains slowly', 'It stores all training data and defers computation to prediction time (no real training phase)', 'It ignores most features', 'It only works on images'], correct: 1 },
    { q: 'The bias-variance tradeoff describes:', options: ['Dataset size vs model complexity', 'The tension between underfitting (bias) and overfitting (variance)', 'Training speed vs accuracy', 'L1 vs L2 regularization'], correct: 1 },
    { q: 'L1 regularization (Lasso) is unique because:', options: ['It increases model complexity', 'It can shrink feature weights to exactly zero — performing feature selection', "It's slower than L2", 'It only applies to neural networks'], correct: 1 },
    { q: 'K-Fold Cross Validation improves on a single train/test split by:', options: ['Using more data', 'Rotating which slice is the test set K times — averaging results for a fairer estimate', 'Removing outliers', 'Reducing overfitting directly'], correct: 1 },
    { q: 'Random Forest combines predictions from:', options: ['K-Means clusters', 'Many Decision Trees trained on random data subsets — majority vote wins', 'One neural network with random seeds', 'Several logistic regression models averaged'], correct: 1 },
    { q: 'Precision is defined as:', options: ['TP / (TP + FN)', 'TP / (TP + FP)', 'TN / (TN + FP)', '(TP + TN) / Total'], correct: 1 },
    { q: 'Recall (Sensitivity) is defined as:', options: ['TP / (TP + FP)', 'TN / (TN + FN)', 'TP / (TP + FN)', '(TP + TN) / Total'], correct: 2 },
    { q: 'F1 Score is the:', options: ['Average of Precision and Recall', 'Harmonic mean of Precision and Recall — punishes imbalance between them', 'Square root of accuracy', 'Sum of TP + TN'], correct: 1 },
    { q: 'K-Means clustering assigns points to groups by:', options: ['Supervised label matching', 'Iteratively assigning each point to the nearest centroid and updating centroid positions', 'Density-based region growing', 'Hierarchical dendrogram cutting'], correct: 1 },
    { q: 'PCA (Principal Component Analysis) is used for:', options: ['Classification', 'Clustering', 'Dimensionality reduction — compressing data while preserving maximum variance', 'Training neural networks faster'], correct: 2 },
    { q: "In a neural network, the 'activation function' determines:", options: ['How fast training runs', "Whether (and how much) a neuron 'fires' its output", 'The number of training epochs', 'The loss function shape'], correct: 1 },
    { q: 'Backpropagation is the process of:', options: ['Moving data backward through the dataset', 'Calculating gradients and flowing errors backward through network layers to update weights', 'Running the model on test data', 'Cleaning input data'], correct: 1 },
    { q: 'Which activation function outputs zero for negative inputs and linear for positive?', options: ['Sigmoid', 'Tanh', 'ReLU (Rectified Linear Unit)', 'Softmax'], correct: 2 },
    { q: 'Mini-batch gradient descent uses:', options: ['All data per update step', 'One example per update step', 'A small random subset (32–256 examples) per update step', 'No data — only random weights'], correct: 2 },
    { q: 'DBSCAN is preferred over K-Means when:', options: ['You have a small dataset', 'Clusters have arbitrary shapes or you want automatic outlier detection', 'You know K in advance', 'You have labelled data'], correct: 1 },
    { q: "The 'elbow method' is used to:", options: ['Tune SVM hyperparameters', 'Choose the optimal K in K-Means clustering', 'Set the learning rate', 'Select regularization type'], correct: 1 },
    { q: 'Model deployment means:', options: ['Deleting the model', 'Making the trained model available to make predictions on new real-world data', 'Retraining the model', 'Cleaning the training data again'], correct: 1 },
    { q: 'Model drift refers to:', options: ['Overfitting during training', "A trained model's performance degrading over time as real-world data patterns change", 'A syntax error in the code', 'Switching from one model type to another'], correct: 1 },
    { q: 'Algorithmic bias most commonly originates from:', options: ['Programming bugs', 'Biased or unrepresentative training data reflecting historical inequalities', 'Too much training data', 'Using Python instead of R'], correct: 1 },
    { q: "The 'explainability' requirement in GDPR affects ML because:", options: ['It bans neural networks', 'Automated decisions affecting people must be explainable — black-box models may not qualify', 'It requires open-source code', 'It mandates specific accuracy thresholds'], correct: 1 },
    { q: 'Which is the best algorithm for image classification?', options: ['Linear Regression', 'K-Means', 'Convolutional Neural Network (CNN)', 'K-Nearest Neighbors'], correct: 2 },
    { q: 'Hyperparameters differ from parameters because:', options: ['They are learned during training', 'They are set before training (e.g., K in KNN, depth in Decision Tree)', 'They do not affect model performance', 'They are only used in neural networks'], correct: 1 },
    { q: 'Grid Search CV finds the best hyperparameters by:', options: ['Random guessing once', 'Trying every specified combination of hyperparameter values with cross-validation', 'Using gradient descent on the hyperparameter space', 'Only testing on the training set'], correct: 1 },
    { q: 'One-hot encoding is used to:', options: ['Speed up matrix multiplication', 'Convert categorical variables into binary columns that ML algorithms can process', 'Remove low-importance features', 'Normalise numerical values to 0–1'], correct: 1 },
    { q: 'Feature scaling (normalisation/standardisation) is most important for:', options: ['Decision Trees', 'Algorithms using distance (KNN, SVM) or gradient descent (Logistic Regression, Neural Networks)', 'Random Forests', 'K-Means only'], correct: 1 },
    { q: 'The ROC-AUC score of 1.0 means:', options: ['The model is useless', 'The model has 50% accuracy (random guessing)', 'The model perfectly separates all positive and negative examples', 'The loss function is minimised'], correct: 2 },
    { q: 'Stratified K-Fold preserves:', options: ['Training speed', 'The class proportion in each fold — critical for imbalanced datasets', 'Feature order', 'The random seed'], correct: 1 },
    { q: 'SVM (Support Vector Machine) finds the:', options: ['Tightest cluster centroid', 'Boundary with maximum margin between two classes', 'Most frequent class', 'Smallest decision tree'], correct: 1 },
    { q: "The 'kernel trick' in SVM enables:", options: ['Faster training', 'Handling non-linearly separable data by implicitly mapping to higher dimensions', 'Automatic feature selection', 'Multi-class classification only'], correct: 1 },
    { q: 'Ensemble methods consistently outperform individual models because:', options: ['They use more memory', 'Combining diverse models reduces variance and averages out individual errors', 'They train faster', 'They require less data'], correct: 1 },
    { q: 'In a content pipeline for ML projects, what should Step 1 always be?', options: ['Model deployment', 'Writing the model code', 'Data collection and understanding (EDA)', 'Hyperparameter tuning'], correct: 2 },
    { q: 'The best way to handle missing values in a dataset is:', options: ['Always delete the row', 'Always fill with the mean', 'Context-dependent: delete, fill, or use a model — choose based on the data and task', 'Ignore them — ML handles it automatically'], correct: 2 },
    { q: 'Epoch in neural network training refers to:', options: ['One update to a single weight', 'One complete pass through the entire training dataset', 'The final test evaluation', 'The architecture (layers and neurons)'], correct: 1 },
    { q: 'Cross-Entropy Loss is used for:', options: ['Regression — measuring continuous error', 'Classification — measuring the penalty for wrong probability predictions', 'Clustering — measuring intra-cluster distance', 'Dimensionality reduction'], correct: 1 },
    { q: 'What is a feature store?', options: ['A shop that sells datasets', 'A centralised repository where computed features are stored and shared across ML teams', 'A type of neural network layer', 'A database backup system'], correct: 1 },
    { q: 'Which metric should a medical diagnostic model optimise for (to catch all sick patients)?', options: ['Precision — minimise false positives', 'Recall — minimise false negatives (missing sick patients is most dangerous)', 'Accuracy — overall correctness', 'AUC — only for multi-class'], correct: 1 },
    { q: 'What makes dimensionality reduction valuable before clustering?', options: ['It adds more features', 'It removes noise and multicollinearity, making distance-based clustering more meaningful', 'It increases the number of clusters needed', 'It converts supervised to unsupervised problems'], correct: 1 },
    { q: 'TensorFlow and PyTorch are used for:', options: ['Data cleaning', 'Building and training deep learning models with GPU acceleration', 'Statistical hypothesis testing', 'SQL database queries'], correct: 1 },
    { q: 'A well-structured ML portfolio project should include:', options: ['Just the final accuracy number', 'Problem statement → data → approach → code → results → business insight', 'Only the Jupyter notebook with no explanation', 'A list of all algorithms learned'], correct: 1 },
    { q: 'The most important skill an ML practitioner brings to a business is:', options: ['Knowing the most complex algorithms', 'Translating business problems into ML solutions and communicating results to non-technical stakeholders', 'Writing the fastest code', 'Using the largest possible neural network'], correct: 1 },
    { q: 'Your certification score in this exam determines:', options: ['Nothing', 'Completion certificate at 70%+ OR Job Guarantee activation at 89%+', 'How much you pay', 'Your course access level'], correct: 1 },
  ],
};
