export const MONTH_1 = {
  id: 1,
  title: 'Foundations of Machine Learning',
  color: '#10B981',
  icon: '🌱',
  quizAfter: 'quiz1',
  quizTitle: 'Fun Quiz #1: ML Foundations Showdown',
  weeks: [
    {
      week: 1,
      title: 'What is Machine Learning?',
      lessons: [
        {
          id: 'ml.1.1.1',
          title: 'AI vs ML vs Deep Learning — The Difference Explained',
          duration: '8 min',
          type: 'video',
          preview: "Imagine a Russian doll — AI is the biggest, ML is inside it, Deep Learning is the smallest one inside ML. In 8 minutes, you'll confidently explain all three at a dinner party.",
          content: [
            'The three-doll analogy: AI → ML → Deep Learning',
            "What 'learning from data' actually means",
            'How ML is different from traditional programming rules',
            '5 real-world examples of ML you use every day',
            'Hands-on: Spot ML vs traditional software in 10 apps',
          ],
        },
        {
          id: 'ml.1.1.2',
          title: 'How Computers Learn: The Netflix Recommendation Story',
          duration: '10 min',
          type: 'video',
          preview: "Netflix doesn't hire thousands of editors to choose your shows. It uses ML. In this lesson, you'll trace exactly how the algorithm decides what's on your homepage — step by step.",
          content: [
            'Training data: what Netflix collects about you',
            'Features and labels explained through recommendations',
            'How the model improves with every watch/skip',
            "Why 'garbage data' leads to 'garbage recommendations'",
            'Hands-on: Map the ML pipeline of an app you use',
          ],
        },
        {
          id: 'ml.1.1.3',
          title: 'The 3 Types of Machine Learning (With Zero Math)',
          duration: '12 min',
          type: 'video',
          preview: "Supervised, Unsupervised, Reinforcement. These sound scary but are incredibly intuitive. By the end of this lesson, you'll explain all three using everyday analogies — no equations required.",
          content: [
            'Supervised Learning: the textbook-with-answer-key analogy',
            'Unsupervised Learning: exploring a city with no map',
            'Reinforcement Learning: learning to ride a bike by falling',
            '10 real-world examples sorted by type',
            'Hands-on: Classify 15 ML applications by type',
          ],
        },
        {
          id: 'ml.1.1.4',
          title: 'Your ML Toolkit Setup Lab',
          duration: '15 min',
          type: 'lab',
          preview: "We'll use Google Colab — a free, browser-based Python notebook — so you can run real ML code without installing anything. This lab gets you set up and running your first model output in 15 minutes.",
          content: [
            'Create your free Google Colab account',
            'Run your first Python cell (just 3 lines!)',
            'Load a real dataset — the Iris flowers dataset',
            'See ML output: predicted flower species',
            'Lab: Save your notebook to your Drive for the course',
          ],
        },
      ],
    },
    {
      week: 2,
      title: 'Data: The Fuel of Machine Learning',
      lessons: [
        {
          id: 'ml.1.2.1',
          title: 'What Is a Dataset? Features, Labels & Rows Explained',
          duration: '8 min',
          type: 'video',
          preview: 'A dataset is just a very smart spreadsheet. Rows are examples, columns are features, and one column is the answer (label). Understand this and 70% of ML makes sense immediately.',
          content: [
            'Datasets as spreadsheets: rows = examples, columns = features',
            "What a 'label' is and why it matters for supervised learning",
            'Numeric vs categorical features',
            'Missing data: what happens when a cell is empty',
            'Hands-on: Analyse the Titanic dataset — spot features and labels',
          ],
        },
        {
          id: 'ml.1.2.2',
          title: 'Garbage In, Garbage Out: Why Data Quality is Everything',
          duration: '10 min',
          type: 'video',
          preview: "Amazon's hiring AI famously discriminated against women. Not because the AI was evil — because the training data was biased. This lesson shows you how data quality ruins (or makes) ML models.",
          content: [
            'The Amazon AI hiring disaster — a case study',
            '5 types of data problems that break ML models',
            'Data cleaning: removing nulls, fixing typos, removing duplicates',
            'Data bias: how it sneaks in and how to spot it',
            'Hands-on: Find and fix data quality issues in a sample dataset',
          ],
        },
        {
          id: 'ml.1.2.3',
          title: 'Train/Test Split: The Golden Rule of ML',
          duration: '8 min',
          type: 'video',
          preview: "Would you study past exam papers and then use the SAME papers as your actual exam? Of course not. That's why we split data into training and testing sets — the ML equivalent of new exam papers.",
          content: [
            "Why you can't train and test on the same data",
            'The 80/20 split rule — and when to break it',
            "Overfitting: when your model 'cheats' on the test",
            "Underfitting: when your model didn't learn enough",
            'Hands-on: Split a dataset and measure the difference',
          ],
        },
        {
          id: 'ml.1.2.4',
          title: 'Feature Engineering: Making Your Data Smarter',
          duration: '12 min',
          type: 'lab',
          preview: "Raw data is rarely ready for ML. Feature engineering is the art of creating better inputs from existing ones — like calculating 'age at purchase' from a birthday and purchase date. Small changes, huge accuracy gains.",
          content: [
            'Feature scaling: why units matter (kg vs grams breaks models)',
            'One-hot encoding: turning categories into numbers',
            'Creating new features from existing ones',
            'Dropping useless features (feature selection)',
            'Lab: Engineer 5 new features from a raw dataset',
          ],
        },
      ],
    },
    {
      week: 3,
      title: 'Your First ML Model',
      lessons: [
        {
          id: 'ml.1.3.1',
          title: 'What Is a Model? The Prediction Machine Explained',
          duration: '8 min',
          type: 'video',
          preview: 'A model is like a trained employee. You train them with examples, they learn the pattern, then you give them new situations and they predict the outcome. This lesson demystifies what a model actually is.',
          content: [
            'Model = a mathematical function that maps inputs to outputs',
            "Parameters: the 'knowledge' stored in a trained model",
            'How a model uses features to make predictions',
            'The difference between a model, an algorithm, and a prediction',
            "Hands-on: See a model's decision boundaries visualised",
          ],
        },
        {
          id: 'ml.1.3.2',
          title: 'Build Your First Real Model (Classifying Flowers)',
          duration: '15 min',
          type: 'lab',
          preview: "The Iris dataset has 150 flowers with 4 measurements each. In this lab, you'll build a model that correctly predicts the species. 5 lines of code. Real output. Real ML.",
          content: [
            'Load the Iris dataset from sklearn',
            'Prepare features (X) and labels (y)',
            'Train a Decision Tree classifier (3 lines of code)',
            'Run predictions on test data',
            "Lab: Measure your model's accuracy — beat 90%!",
          ],
        },
        {
          id: 'ml.1.3.3',
          title: "Reading Model Results: What Does 'Accuracy' Actually Mean?",
          duration: '10 min',
          type: 'video',
          preview: "Your model says 90% accuracy. Great! But what if 90% of the dataset is one class? You'd get 90% by always predicting that class without learning anything. Accuracy is not the only metric that matters.",
          content: [
            'Accuracy: correct predictions / total predictions',
            'When accuracy is misleading (imbalanced classes)',
            'Confusion matrix: the full picture in a 2×2 grid',
            'Precision vs Recall — and when each matters more',
            'Hands-on: Calculate metrics for your Iris model',
          ],
        },
        {
          id: 'ml.1.3.4',
          title: 'Month 1 Mini-Project: Predict House Prices',
          duration: '20 min',
          type: 'project',
          preview: "Apply everything from Month 1. You'll load a real house pricing dataset, clean the data, engineer 3 features, train a model, and report its accuracy. This goes straight into your portfolio.",
          content: [
            'Load the California Housing dataset',
            'Clean: handle missing values and outliers',
            "Engineer: create 'price_per_room' feature",
            'Train a Linear Regression model',
            'Project: Document your results and submit',
          ],
        },
      ],
    },
    {
      week: 4,
      title: 'Regression Deep Dive',
      lessons: [
        {
          id: 'ml.1.4.1',
          title: 'Linear Regression: Drawing the Best Line Through Data',
          duration: '10 min',
          type: 'video',
          preview: "Linear regression finds the single best straight line through a cloud of data points. The 'best' line minimises the average distance to every point. Understand this and you understand the heart of supervised learning.",
          content: [
            'What a regression line represents',
            'The equation: y = mx + b made human-readable',
            'Mean Squared Error: measuring how bad our line is',
            "Why we need the 'best fit' — not just any line",
            'Hands-on: Draw regression lines and compare MSE scores',
          ],
        },
        {
          id: 'ml.1.4.2',
          title: 'How the Model Learns: Gradient Descent in Plain English',
          duration: '12 min',
          type: 'video',
          preview: "Imagine you're blindfolded on a hilly landscape, trying to reach the lowest point. You feel the slope under your feet and take small steps downhill. That's gradient descent — and it's how every neural network learns.",
          content: [
            'The hill-walking analogy for gradient descent',
            'Learning rate: step size matters — too big, too small',
            "Loss function: the 'altitude' we're trying to minimise",
            'Iterations: how many steps until we converge',
            'Hands-on: Visualise gradient descent on a loss surface',
          ],
        },
        {
          id: 'ml.1.4.3',
          title: 'Multiple Regression: Predicting with Many Features',
          duration: '10 min',
          type: 'video',
          preview: "House price depends on size AND location AND number of rooms. Multiple regression handles all features simultaneously. It's literally the same maths — just more dimensions.",
          content: [
            'From one feature to many: same principle, more inputs',
            'Multicollinearity: when features are too similar',
            'Feature importance: which input matters most?',
            'Visualising multi-dimensional regression',
            'Hands-on: Train a multi-feature house price model',
          ],
        },
        {
          id: 'ml.1.4.4',
          title: 'Regression Lab + Quiz 1 Prep',
          duration: '15 min',
          type: 'lab',
          preview: 'Consolidate your regression skills with a real salary prediction challenge, then review the key concepts from Weeks 1–4 before the quiz. Every quiz question comes from something in this lab prep.',
          content: [
            'Lab: Build a salary predictor from experience + education',
            'Review: ML types, features, labels, train/test split',
            'Review: Linear regression, MSE, gradient descent',
            'Review: Accuracy, confusion matrix, precision, recall',
            'Prep: 10 practice questions — same format as Quiz 1',
          ],
        },
      ],
    },
  ],
};
