export const MONTH_3 = {
  id: 3,
  title: 'Advanced Topics & Certification',
  color: '#F59E0B',
  icon: '🏆',
  quizAfter: null,
  weeks: [
    {
      week: 9,
      title: 'Unsupervised Learning',
      lessons: [
        {
          id: 'ml.3.9.1',
          title: 'K-Means Clustering: Grouping Without Labels',
          duration: '10 min',
          type: 'video',
          preview: "Spotify groups listeners into 'taste profiles' without asking anyone. Netflix clusters films without human-defined genres. K-Means finds natural groups in data — no labels needed. Pure unsupervised learning.",
          content: [
            'The clustering problem: grouping without answers',
            'K-Means algorithm: assign → update → repeat',
            'Choosing K: the elbow method',
            'Visualising clusters in 2D and 3D',
            'Hands-on: Cluster customers by purchase behaviour',
          ],
        },
        {
          id: 'ml.3.9.2',
          title: 'Hierarchical Clustering & DBSCAN',
          duration: '10 min',
          type: 'video',
          preview: 'K-Means needs you to choose K upfront. Hierarchical clustering builds a tree of every possible grouping so you can see them all. DBSCAN finds clusters of any shape and identifies outliers automatically.',
          content: [
            'Hierarchical: dendrogram and how to cut it',
            'DBSCAN: density-based clusters, no K required',
            'Comparing K-Means vs Hierarchical vs DBSCAN',
            'When outliers are actually more interesting than clusters',
            'Hands-on: Anomaly detection with DBSCAN',
          ],
        },
        {
          id: 'ml.3.9.3',
          title: 'Dimensionality Reduction: PCA in Plain English',
          duration: '12 min',
          type: 'video',
          preview: "You have 500 features. Most of them are correlated or useless. PCA compresses them into a smaller set of components that capture the most variance. Think of it as 'summarising' your data without losing the key information.",
          content: [
            'The curse of dimensionality: why 500 features hurts',
            'PCA: rotating data to find the axes of most variance',
            'Explained variance: how many components to keep',
            'Visualising high-dimensional data in 2D with PCA',
            'Hands-on: PCA on the MNIST handwritten digits dataset',
          ],
        },
        {
          id: 'ml.3.9.4',
          title: 'Unsupervised Learning Lab',
          duration: '20 min',
          type: 'lab',
          preview: 'Run a full unsupervised pipeline: cluster customers, reduce dimensions with PCA, then visualise the results. The kind of analysis startups pay freelancers ₹5,000–₹15,000 to do.',
          content: [
            'Load a retail customer transactions dataset',
            'K-Means: segment customers into 4 buying profiles',
            'PCA: compress 20 features to 2 for visualisation',
            'Plot the clusters in 2D — beautiful output',
            'Lab: Write a 200-word business insight report',
          ],
        },
      ],
    },
    {
      week: 10,
      title: 'Introduction to Neural Networks',
      lessons: [
        {
          id: 'ml.3.10.1',
          title: 'Neural Networks: Neurons, Layers, and Weights',
          duration: '12 min',
          type: 'video',
          preview: "A neural network is just logistic regression applied many times in sequence. Each layer transforms the data a little more. By the final layer, even messy raw inputs become clean predictions. The 'deep' in Deep Learning means many layers.",
          content: [
            'Neurons: weighted sum + activation function',
            'Layers: input, hidden, output',
            'Weights and biases: the learnable parameters',
            'Forward pass: how data flows through the network',
            'Hands-on: Visualise a neural network making a prediction',
          ],
        },
        {
          id: 'ml.3.10.2',
          title: 'Backpropagation: How Networks Learn',
          duration: '12 min',
          type: 'video',
          preview: "The network makes a prediction, measures how wrong it is, then works backwards through every layer adjusting weights to be less wrong next time. Repeat 10,000 times. That's backpropagation — and it runs at the heart of every AI you've heard of.",
          content: [
            'Forward pass → loss → backward pass cycle',
            'How errors flow back through layers',
            'Gradient descent for multi-layer networks',
            'Activation functions: ReLU, Sigmoid, Tanh',
            'Hands-on: Watch loss decrease over 100 epochs',
          ],
        },
        {
          id: 'ml.3.10.3',
          title: 'Build Your First Neural Network',
          duration: '15 min',
          type: 'lab',
          preview: "Using TensorFlow/Keras — the industry standard — you'll build a 3-layer neural network in 10 lines of code and train it on real data. Welcome to deep learning.",
          content: [
            'Build a Sequential model: Input → Dense → Dense → Output',
            'Compile: choose optimiser, loss, and metric',
            'Train: model.fit() with epochs and batch size',
            'Evaluate on test data — measure accuracy',
            'Lab: Beat 95% accuracy on the Fashion-MNIST dataset',
          ],
        },
        {
          id: 'ml.3.10.4',
          title: 'When to Use Neural Networks (and When NOT To)',
          duration: '10 min',
          type: 'video',
          preview: 'Neural networks are powerful but not always the answer. A Random Forest on a 1,000-row CSV will often beat a neural network. This lesson gives you a decision framework for choosing the right tool.',
          content: [
            'Neural networks win: images, text, audio, huge datasets',
            'Classical ML wins: small data, tabular data, explainability',
            'The complexity-accuracy tradeoff',
            'Compute cost: why neural networks are expensive',
            'Hands-on: Algorithm selection challenge — 10 scenarios',
          ],
        },
      ],
    },
    {
      week: 11,
      title: 'ML in the Real World',
      lessons: [
        {
          id: 'ml.3.11.1',
          title: 'The End-to-End ML Pipeline in Industry',
          duration: '12 min',
          type: 'video',
          preview: 'In industry, ML is 80% data wrangling and 20% modelling. This lesson walks you through the full production ML pipeline: data collection → cleaning → training → evaluation → deployment → monitoring.',
          content: [
            'Data collection and storage at scale',
            'Feature stores: sharing features across teams',
            'Model versioning and experiment tracking (MLflow)',
            'Model deployment: the final 10% that trips everyone up',
            'Monitoring: detecting model drift in production',
          ],
        },
        {
          id: 'ml.3.11.2',
          title: 'Ethics in Machine Learning: Fairness & Bias',
          duration: '10 min',
          type: 'video',
          preview: "Facial recognition fails more on darker skin tones. Credit scoring models disadvantage minorities. These aren't bugs — they're features of biased training data. This lesson teaches you to audit your models for fairness.",
          content: [
            'Types of algorithmic bias and where they come from',
            'Fairness metrics: demographic parity, equal opportunity',
            'How to audit your model for bias',
            "The GDPR and 'right to explanation'",
            'Hands-on: Bias audit on a credit scoring dataset',
          ],
        },
        {
          id: 'ml.3.11.3',
          title: 'Freelancing as an ML Practitioner',
          duration: '10 min',
          type: 'video',
          preview: "ML freelancers on Upwork charge ₹3,000–₹15,000 per project. Companies need data analysis, model building, and automation — and they can't afford to hire a full-time data scientist. You can fill that gap.",
          content: [
            'Most in-demand ML freelance services',
            'Building a portfolio of 3 case studies',
            'Pricing your services (hourly vs project-based)',
            'Finding your first client on Upwork/Fiverr/LinkedIn',
            'Hands-on: Write your Upwork ML profile bio',
          ],
        },
        {
          id: 'ml.3.11.4',
          title: 'Portfolio Builder Lab: Your Top 3 Projects',
          duration: '20 min',
          type: 'lab',
          preview: 'Compile your best 3 projects from this course into portfolio-worthy case studies. Each case study follows the format: Problem → Data → Approach → Results → Insights. This lab outputs your job-application-ready portfolio.',
          content: [
            'Select your 3 strongest course projects',
            'Write a case study for each: 200 words + key metrics',
            'Create a GitHub repository for your ML portfolio',
            'Add project notebooks and README files',
            'Lab: Share your GitHub link — get peer feedback',
          ],
        },
      ],
    },
    {
      week: 12,
      title: 'Review & Certification',
      lessons: [
        {
          id: 'ml.3.12.1',
          title: 'Complete Review: Foundations & Data',
          duration: '15 min',
          type: 'review',
          preview: 'Rapid-fire review of Month 1 content — ML types, datasets, features, labels, train/test split, feature engineering, linear regression, gradient descent, and evaluation metrics. Every concept in a single structured session.',
          content: [
            'Review: AI vs ML vs Deep Learning',
            'Review: Features, labels, train/test split',
            'Review: Data quality and feature engineering',
            'Review: Linear regression, MSE, gradient descent',
            'Practice: 15 rapid-fire Foundation questions',
          ],
        },
        {
          id: 'ml.3.12.2',
          title: 'Complete Review: Algorithms & Evaluation',
          duration: '15 min',
          type: 'review',
          preview: 'Full Month 2 review — classification algorithms, overfitting fixes, evaluation metrics, hyperparameter tuning, and ensemble methods. Includes 15 practice questions in exam format.',
          content: [
            'Review: Logistic Regression, Decision Trees, KNN',
            'Review: Bias-variance, L1/L2, cross-validation',
            'Review: Precision, Recall, F1, ROC-AUC',
            'Review: Random Forest, SVM, hyperparameter tuning',
            'Practice: 15 Algorithm questions in exam format',
          ],
        },
        {
          id: 'ml.3.12.3',
          title: 'Complete Review: Advanced Topics & Applications',
          duration: '15 min',
          type: 'review',
          preview: 'Month 3 review — K-Means, PCA, neural networks, backpropagation, industry pipelines, ethics, and career strategy. Plus 20 mock exam questions at certification difficulty.',
          content: [
            'Review: K-Means, Hierarchical Clustering, DBSCAN, PCA',
            'Review: Neural Networks, backpropagation, activation functions',
            'Review: Industry pipelines, model deployment, monitoring',
            'Review: Ethics, fairness, algorithmic bias',
            'Practice: 20 mock certification questions',
          ],
        },
        {
          id: 'ml.3.12.4',
          title: 'Certification Exam',
          duration: '60 min',
          type: 'exam',
          preview: "50 questions. 60 minutes. All 12 weeks tested. Score 70%+ to earn your Certified ML Practitioner certificate. Score 89%+ to activate the Job Guarantee. University of Tübingen partnership credential. You're ready.",
          content: [
            'Part 1: Core Concepts MCQ (20 questions × 2 pts)',
            'Part 2: Applied Scenarios (10 questions × 4 pts)',
            'Part 3: True/False Speed Round (10 × 1 pt)',
            'Bonus: 2 Challenge Questions (+5 pts each)',
            'Passing: 70% | Job Guarantee: 89%+ | Certificate within 24h',
          ],
        },
      ],
    },
  ],
};
