export const MONTH_2 = {
  id: 2,
  title: 'Core Algorithms',
  color: '#7C6DFA',
  icon: '⚡',
  quizAfter: 'quiz2',
  quizTitle: 'Fun Quiz #2: Algorithm Master Challenge',
  weeks: [
    {
      week: 5,
      title: 'Classification Algorithms',
      lessons: [
        {
          id: 'ml.2.5.1',
          title: 'Logistic Regression: When the Answer is Yes or No',
          duration: '10 min',
          type: 'video',
          preview: "Despite the name, Logistic Regression is a classification algorithm. It predicts probability — 'there's an 87% chance this email is spam.' The sigmoid function squishes any number into 0–1. Nothing complicated happening here.",
          content: [
            'Logistic vs Linear Regression: the key difference',
            'The sigmoid function: squishing numbers into 0–1',
            "Decision boundary: where does 'yes' become 'no'?",
            'How to read a classification probability score',
            'Hands-on: Build a spam/not-spam classifier',
          ],
        },
        {
          id: 'ml.2.5.2',
          title: 'Decision Trees: The 20-Questions Algorithm',
          duration: '12 min',
          type: 'video',
          preview: "A Decision Tree is literally like the game 20 Questions. 'Is it bigger than a car? Does it have fur?' Each question splits the possibilities until you reach an answer. ML just learns the best questions from data.",
          content: [
            'How trees split data at each node',
            'Information gain: choosing the best question',
            'Depth control: stopping the tree before it overfits',
            'Visualising your Decision Tree',
            'Hands-on: Build and visualise a fraud detection tree',
          ],
        },
        {
          id: 'ml.2.5.3',
          title: "K-Nearest Neighbors: Find Your Data's Neighbours",
          duration: '8 min',
          type: 'video',
          preview: "KNN is hilariously simple: 'What are the K closest examples to this new point? What are they labelled? That's probably what the new point is.' No training required. Just memory and distance.",
          content: [
            'How KNN classifies by majority vote of neighbours',
            'Choosing K: too small = noisy, too big = blurry',
            'Distance metrics: Euclidean distance explained',
            "Why KNN is 'lazy' (no real training phase)",
            'Hands-on: KNN on digit recognition (0–9)',
          ],
        },
        {
          id: 'ml.2.5.4',
          title: 'Classification Showdown Lab',
          duration: '15 min',
          type: 'lab',
          preview: 'Run the same dataset through Logistic Regression, Decision Tree, and KNN. Compare their accuracy, speed, and how they draw decision boundaries. Winner gets used in your portfolio project.',
          content: [
            'Load a heart disease classification dataset',
            'Train all three classifiers with identical settings',
            'Compare accuracy, precision, recall, and F1',
            "Visualise each model's decision boundary side by side",
            'Lab: Declare a winner and justify your choice',
          ],
        },
      ],
    },
    {
      week: 6,
      title: 'Fighting Overfitting',
      lessons: [
        {
          id: 'ml.2.6.1',
          title: 'The Bias-Variance Tradeoff: Finding the Sweet Spot',
          duration: '10 min',
          type: 'video',
          preview: 'Bias = your model is too simple and wrong everywhere. Variance = your model is obsessed with training data and wrong on new data. You need the sweet spot between them. This is the most important concept in all of ML.',
          content: [
            'High bias = underfitting: the model is too simple',
            'High variance = overfitting: the model memorised training data',
            'The sweet spot: low bias AND low variance',
            'Visualising bias vs variance with learning curves',
            'Hands-on: Diagnose underfitting vs overfitting in 5 models',
          ],
        },
        {
          id: 'ml.2.6.2',
          title: 'Regularization: L1 (Lasso) and L2 (Ridge)',
          duration: '12 min',
          type: 'video',
          preview: 'Regularization is a tax on complexity. If your model wants to be complex, it pays a penalty. L1 (Lasso) can zero out features entirely — effectively selecting them. L2 (Ridge) shrinks all features gently. Both fight overfitting.',
          content: [
            'What regularization adds to the loss function',
            'L2 / Ridge: shrinks weights, keeps all features',
            'L1 / Lasso: zeros out weak features — automatic selection',
            'The lambda hyperparameter: how much to penalise',
            'Hands-on: Compare regularised vs unregularised models',
          ],
        },
        {
          id: 'ml.2.6.3',
          title: 'Cross-Validation: The Fairer Way to Test Your Model',
          duration: '10 min',
          type: 'video',
          preview: 'One train/test split gives you one lucky (or unlucky) score. K-Fold Cross Validation runs K experiments, each using a different test set. The average is a much more honest picture of real-world performance.',
          content: [
            'Why a single split can be misleading',
            'K-Fold: rotate which slice is the test set',
            'Stratified K-Fold: preserving class balance in each fold',
            'When to use 5-fold vs 10-fold',
            'Hands-on: Cross-validate your Week 5 classifiers',
          ],
        },
        {
          id: 'ml.2.6.4',
          title: 'Ensemble Methods: Why Teams Beat Individuals',
          duration: '12 min',
          type: 'lab',
          preview: "Random Forest = 100 Decision Trees voting. Each tree sees slightly different data. Combined, they're dramatically more accurate than any single tree. Ensemble methods consistently win ML competitions.",
          content: [
            'Bagging: train many models on random subsets — then vote',
            'Random Forest: bagged trees with random feature selection',
            "Boosting: each model learns from the last model's mistakes",
            'When to use ensembles vs simple models',
            'Lab: Random Forest vs single Decision Tree — accuracy comparison',
          ],
        },
      ],
    },
    {
      week: 7,
      title: 'Model Evaluation & Metrics',
      lessons: [
        {
          id: 'ml.2.7.1',
          title: 'The Full Metrics Toolkit: Beyond Accuracy',
          duration: '10 min',
          type: 'video',
          preview: "A COVID test that always says 'negative' is 99% accurate if only 1% of people have COVID. Clearly useless. Precision, Recall, F1, and ROC-AUC give you the real picture.",
          content: [
            'Accuracy, Precision, Recall — all in one visual',
            'F1 Score: the harmonic mean of Precision and Recall',
            'When to optimise Precision vs Recall (medical vs spam)',
            'ROC Curve: visualising classifier performance across thresholds',
            'AUC: comparing classifiers with a single number',
          ],
        },
        {
          id: 'ml.2.7.2',
          title: 'Confusion Matrix Deep Dive',
          duration: '8 min',
          type: 'video',
          preview: 'Four cells. TP, TN, FP, FN. Every metric in ML flows from these four numbers. Master the confusion matrix and you master model evaluation forever.',
          content: [
            'The 4 cells: True Positive, True Negative, False Positive, False Negative',
            'Deriving Precision, Recall, Accuracy from the matrix',
            'Reading multi-class confusion matrices',
            'The cost of each type of error (medical vs spam context)',
            'Hands-on: Compute all metrics from a raw confusion matrix',
          ],
        },
        {
          id: 'ml.2.7.3',
          title: 'Hyperparameter Tuning: Finding the Best Model Settings',
          duration: '12 min',
          type: 'video',
          preview: 'Hyperparameters are the knobs you set BEFORE training — like how deep your tree goes, or what K to use in KNN. Grid Search tries every combination. Random Search is smarter. This lesson shows you both.',
          content: [
            'Parameters vs hyperparameters: the key distinction',
            'Grid Search: try every combination (slow but thorough)',
            'Random Search: sample the space (faster, often as good)',
            'Cross-validation inside Grid Search — nested CV',
            'Hands-on: Tune a Random Forest to beat baseline accuracy',
          ],
        },
        {
          id: 'ml.2.7.4',
          title: 'Evaluation Lab + Quiz 2 Prep',
          duration: '15 min',
          type: 'lab',
          preview: 'Run a full model evaluation pipeline on a disease prediction dataset — then review Weeks 5–8 concepts in quiz format so you walk into Quiz 2 fully prepared.',
          content: [
            'Lab: Evaluate 3 models with the full metrics toolkit',
            'Review: Logistic Regression, Decision Tree, KNN',
            'Review: Bias-variance tradeoff, L1/L2, Cross-validation',
            'Review: Precision, Recall, F1, ROC-AUC',
            'Prep: 10 practice questions in Quiz 2 format',
          ],
        },
      ],
    },
    {
      week: 8,
      title: 'Optimisation & Loss Functions',
      lessons: [
        {
          id: 'ml.2.8.1',
          title: "Loss Functions: Teaching the Model What 'Wrong' Means",
          duration: '10 min',
          type: 'video',
          preview: 'The loss function is the GPS distance between where your model is and where it should be. Different tasks need different loss functions — MSE for regression, Cross-Entropy for classification. Get this wrong and your model trains on the wrong target.',
          content: [
            'MSE: Mean Squared Error for regression tasks',
            'MAE: Mean Absolute Error — more robust to outliers',
            'Cross-Entropy Loss for classification',
            'How the loss function shape affects training',
            'Hands-on: Switch loss functions and watch training change',
          ],
        },
        {
          id: 'ml.2.8.2',
          title: 'Gradient Descent Variants: Batch, Mini-Batch, Stochastic',
          duration: '12 min',
          type: 'video',
          preview: 'Full Gradient Descent = look at ALL data before each step (slow). Stochastic = look at ONE example (noisy). Mini-Batch = look at 32–256 examples (the sweet spot, used by every neural network).',
          content: [
            'Batch Gradient Descent: stable but slow',
            'Stochastic GD: fast but noisy — can escape local minima',
            'Mini-Batch GD: the real-world standard',
            'Learning rate schedules: starting fast, slowing down',
            'Hands-on: Compare convergence speed of all three',
          ],
        },
        {
          id: 'ml.2.8.3',
          title: 'Support Vector Machines: Maximum Margin Classifiers',
          duration: '10 min',
          type: 'video',
          preview: 'SVM finds the fattest possible boundary between two classes — the maximum margin. Support vectors are the data points closest to the line. Simple idea, surprisingly powerful results.',
          content: [
            'The maximum margin concept',
            'Support vectors: the points that define the boundary',
            'Kernel trick: handling non-linear data',
            "When SVM beats Decision Trees (and when it doesn't)",
            'Hands-on: SVM on the breast cancer dataset',
          ],
        },
        {
          id: 'ml.2.8.4',
          title: 'Month 2 Capstone: End-to-End Classification Pipeline',
          duration: '25 min',
          type: 'project',
          preview: 'Build a complete ML pipeline from raw data to evaluated model. Choose from customer churn, disease prediction, or sentiment classification. This is the centrepiece of your ML portfolio.',
          content: [
            'Choose your classification problem',
            'Full pipeline: load → clean → engineer → split → train → evaluate',
            'Regularisation + cross-validation applied',
            'Full metrics report: accuracy, F1, ROC-AUC',
            'Project: Write up results and add to portfolio',
          ],
        },
      ],
    },
  ],
};
