export const CERTIFICATION = {
  id: 'certification',
  title: 'Certification Exam',
  subtitle: '50 questions · 60 minutes · Pass: 70% · Job Guarantee: 89%+',
  passingScore: 70,
  jobGuaranteeScore: 89,
  icon: '🏆',
  questions: [
    { q: 'What is the primary function of a Large Language Model?', options: ['Store data', 'Predict the next most likely token in a sequence', 'Browse the internet', 'Run calculations'], correct: 1 },
    { q: 'Which is NOT a component of the RTF framework?', options: ['Role', 'Task', 'Format', 'Timeline'], correct: 3 },
    { q: 'What makes chain-of-thought prompting effective?', options: ["It's shorter", 'It forces the model to show intermediate reasoning steps', 'It uses less tokens', "It's newer"], correct: 1 },
    { q: "How many tokens is the word 'extraordinary' approximately?", options: ['1', '2-3', '5', '10'], correct: 1 },
    { q: 'What is the best use case for few-shot prompting?', options: ['Quick questions', 'When you want output to follow a specific pattern or style', 'Saving tokens', 'System administration'], correct: 1 },
    { q: 'In token pricing, which typically costs more per token?', options: ['Input tokens', 'Output tokens', "They're identical", 'Cached tokens'], correct: 1 },
    { q: "What does 'prompt compression' achieve?", options: ['Makes prompts invisible', 'Reduces token count while preserving output quality', 'Compresses files', 'Speeds up the internet'], correct: 1 },
    { q: 'Which model tier should you use for simple text formatting?', options: ['The most powerful available', 'A smaller, cheaper model like Haiku or GPT-3.5', 'No model is needed', 'A custom-trained model'], correct: 1 },
    { q: 'What is an API key?', options: ['A physical key', 'A unique credential that authenticates your access to an AI service', 'A keyboard shortcut', 'A type of prompt'], correct: 1 },
    { q: 'System prompts are best used for:', options: ['One-time questions', 'Setting persistent behavior rules for the AI across a conversation', 'Saving files', 'Internet browsing'], correct: 1 },
    { q: "What's the main advantage of prompt chaining over single prompts?", options: ["It's cheaper", 'Each step can be optimized independently for quality and cost', "It's simpler", 'It uses no tokens'], correct: 1 },
    { q: 'Which negative prompting technique is most effective?', options: ["'Don't be bad'", "'Do NOT include: introductions, caveats, or filler phrases'", "'Please try not to mess up'", "'Avoid mistakes'"], correct: 1 },
    { q: "What's the 'context window' limit for Claude?", options: ['1,000 tokens', '10,000 tokens', '200,000 tokens', 'Unlimited'], correct: 2 },
    { q: 'When should you start a new conversation instead of continuing?', options: ['Every 5 minutes', 'When the conversation context becomes irrelevant or too long', 'Never', 'Every message'], correct: 1 },
    { q: "What is the CRISP framework's 'P' component?", options: ['Personality', 'Parameters (constraints and format)', 'Programming', 'Patience'], correct: 1 },
    { q: 'Which tool allows no-code AI automation?', options: ['Python only', 'Zapier/Make', 'Command line', 'Assembly language'], correct: 1 },
    { q: 'How does persona prompting improve output quality?', options: ["It doesn't", 'It activates domain-specific knowledge patterns in the model', 'It makes responses shorter', 'It adds emojis'], correct: 1 },
    { q: "What's the token cost of saying 'Please' and 'Thank you' in every prompt?", options: ['Zero', '2-4 tokens that add up over hundreds of prompts', 'It saves tokens', "Tokens aren't real"], correct: 1 },
    { q: "In a content pipeline chain, what should Step 1 always be?", options: ['Writing', 'Editing', 'Research/ideation', 'Publishing'], correct: 2 },
    { q: 'What is the recommended length for custom instructions?', options: ['10,000+ words', 'Under 500 words', '1 sentence', 'No limit exists'], correct: 1 },
    { q: 'Which is a sign of a well-optimized prompt?', options: ["It's very long", 'It achieves the desired output with minimum tokens', 'It uses many adjectives', 'It includes the full conversation history'], correct: 1 },
    { q: "What does 'hallucination' mean in AI context?", options: ['The AI is dreaming', 'The model generates confident but factually incorrect information', 'A system error', 'The user sees things'], correct: 1 },
    { q: 'Temperature setting in AI controls:', options: ['Computer heat', 'Randomness/creativity of responses', 'Speed', 'Token cost'], correct: 1 },
    { q: 'What makes a strong portfolio project for a prompt engineer?', options: ['Screenshots of conversations', 'A documented workflow showing problem → solution → measurable results', 'Just the prompts', 'A long essay about AI'], correct: 1 },
    { q: "What's the first thing to check when AI output quality is poor?", options: ['Internet speed', 'The clarity and specificity of your prompt', 'Time of day', 'AI version number'], correct: 1 },
    { q: 'Prompt engineering as a career skill is valuable because:', options: ["It's a fad", 'AI tools are increasingly central to knowledge work across all industries', 'It replaces all other skills', "It's easy and requires no practice"], correct: 1 },
    { q: "What is 'rate limiting' in API usage?", options: ['Speed of typing', 'A cap on how many requests you can make in a given time period', 'Network speed', 'Token compression'], correct: 1 },
    { q: 'Which is the most token-efficient way to get a list from AI?', options: ["'Give me some ideas about...'", "'List 5 items: [topic]. Format: numbered, one line each, no explanations.'", "'Can you think of things related to...'", "'What are your thoughts on...'"], correct: 1 },
    { q: 'What makes Cursor/Bolt different from traditional coding?', options: ['They use older technology', 'You describe what you want in natural language and AI generates the code', "They don't create real apps", 'They only work offline'], correct: 1 },
    { q: 'The ideal few-shot example count is:', options: ['20+', '2-3 high-quality examples', '0', '100'], correct: 1 },
    { q: "What's the biggest token waste in most conversations?", options: ['Technical terms', 'Unnecessary preamble, repetition, and verbose instructions', 'Short responses', 'Using numbers'], correct: 1 },
    { q: 'A well-structured system prompt should include:', options: ['Your life story', 'Role definition, behavioral rules, output format, and constraints', 'Only one sentence', 'No specific information'], correct: 1 },
    { q: "What is 'cached tokens' in API pricing?", options: ['Deleted tokens', 'Previously processed tokens that cost less on reuse', 'Free tokens', 'Broken tokens'], correct: 1 },
    { q: 'Why is model selection important for token saving?', options: ["It's not important", 'Different models have different costs per token and capability levels', 'All models cost the same', 'Cheaper models are always better'], correct: 1 },
    { q: "What should a prompt engineer's LinkedIn headline include?", options: ["Just 'Looking for work'", "Specific skills: 'Certified Prompt Engineer | AI Workflow Optimization | Token Cost Reduction'", 'Nothing specific', 'Only their degree'], correct: 1 },
    { q: "What's the key benefit of prompt chaining for businesses?", options: ['It looks impressive', 'It creates reproducible, optimizable workflows with quality gates between steps', "It's free", 'It eliminates the need for AI'], correct: 1 },
    { q: 'How should you handle AI output that seems wrong?', options: ['Accept it anyway', 'Verify, then refine your prompt with additional constraints or context', 'Give up', 'Delete everything'], correct: 1 },
    { q: "What's the relationship between prompt length and output quality?", options: ['Longer is always better', 'There is an optimal length — clear and specific without unnecessary filler', 'Shorter is always better', "Length doesn't matter at all"], correct: 1 },
    { q: 'No-code AI tools like Zapier are best for:', options: ['Building operating systems', 'Automating repetitive workflows by connecting AI to existing apps', 'Replacing programmers entirely', 'Only large enterprises'], correct: 1 },
    { q: 'What should the final step of every AI workflow be?', options: ['Deleting history', 'Human review and quality assurance', 'Sending to AI again', 'Nothing'], correct: 1 },
    { q: "What's the most important skill for a prompt engineer?", options: ['Coding in Python', 'Clear thinking and the ability to communicate precisely', 'Mathematics', 'Graphic design'], correct: 1 },
    { q: 'When pricing freelance prompt engineering services, what matters most?', options: ['Charging the lowest rate', 'The measurable value and time saved for the client', 'How fast you type', 'How many prompts you write'], correct: 1 },
    { q: "What's the purpose of negative prompting ('Do NOT...')?", options: ['Being rude to AI', 'Preventing specific unwanted behaviors or content in the output', 'Saving tokens', 'Making prompts longer'], correct: 1 },
    { q: "In the 7 Token-Saving Commandments, what's #1?", options: ['Use emojis', 'Kill the fluff — remove unnecessary words and phrases', 'Write more', 'Use the most expensive model'], correct: 1 },
    { q: 'What distinguishes a certified prompt engineer from a casual AI user?', options: ['Nothing', 'Systematic methodology, measurable results, documented workflows, and cost awareness', 'They use AI more often', 'They have a computer science degree'], correct: 1 },
    { q: 'How do you measure the ROI of a prompt engineering workflow?', options: ["You can't", 'Compare time saved, quality improvement, and token costs against manual alternatives', 'Count the number of prompts', 'Check social media likes'], correct: 1 },
    { q: "What's the ideal structure for a business case study in your portfolio?", options: ['Just show the prompt', 'Problem → Approach → Prompts Used → Results → Token Cost → Impact', 'Write a 10-page essay', 'Just show the AI output'], correct: 1 },
    { q: "What's the future of prompt engineering as a career?", options: ['It will disappear', "It's evolving into AI workflow design, agent orchestration, and AI strategy roles", 'It will stay exactly the same', 'Only for programmers'], correct: 1 },
    { q: "What's the single best practice that saves both tokens AND improves quality?", options: ['Using all caps', 'Being specific and structured in your instructions from the start', 'Writing longer prompts', 'Using multiple AI tools simultaneously'], correct: 1 },
    { q: 'Your certification score determines:', options: ['Nothing', 'Completion certificate (70%+) or Job Guarantee tier (89%+)', 'How much you pay', 'Your AI access level'], correct: 1 },
  ],
};
