export const MONTH_2 = {
  id: 2,
  title: 'Token Mastery',
  color: '#7C6DFA',
  icon: '⚡',
  quizAfter: 'quiz2',
  quizTitle: 'Fun Quiz #2: Token Master Challenge',
  weeks: [
    {
      week: 5,
      title: 'System Prompts & AI Personas',
      lessons: [
        {
          id: '2.5.1',
          title: "System Prompts: Programming AI's Personality",
          duration: '10 min',
          type: 'video',
          preview: 'A system prompt is like giving AI its job description before the interview. It sets the rules, personality, and boundaries for every response that follows.',
          content: [
            'System vs user prompts explained',
            'How system prompts shape every response',
            'The anatomy of a great system prompt',
            'Platform differences (Claude vs ChatGPT)',
            'Hands-on: Write 3 system prompts',
          ],
        },
        {
          id: '2.5.2',
          title: 'Creating Expert Personas That Actually Work',
          duration: '10 min',
          type: 'video',
          preview: 'Want AI to respond like a Harvard professor? A startup mentor? A strict editor? Persona prompts are how you unlock specialized knowledge without specialized AI.',
          content: [
            'The persona formula that works',
            '10 power personas for different tasks',
            'Combining personas for multi-expert analysis',
            'When personas help vs when they hurt',
            'Hands-on: Create your dream team of AI personas',
          ],
        },
        {
          id: '2.5.3',
          title: 'Custom Instructions: Set It and Forget It',
          duration: '8 min',
          type: 'video',
          preview: 'Stop repeating yourself! Custom instructions in Claude and ChatGPT remember your preferences across every conversation. Set up once, benefit forever.',
          content: [
            'Where to find custom instructions',
            'What to include in your profile',
            'Project-specific vs global instructions',
            'The 500-word sweet spot',
            'Hands-on: Set up your custom instructions',
          ],
        },
        {
          id: '2.5.4',
          title: 'Persona Lab: Build Your AI Dream Team',
          duration: '15 min',
          type: 'lab',
          preview: 'Build 5 specialized AI personas for your work — a strategist, an editor, a researcher, a critic, and a creative. Test each one on real tasks.',
          content: [
            'Design 5 role-specific personas',
            'Test each persona on identical tasks',
            'Compare output quality across personas',
            'Create your persona template library',
            'Lab: Deploy your AI team on a real project',
          ],
        },
      ],
    },
    {
      week: 6,
      title: 'Token Economics 101',
      lessons: [
        {
          id: '2.6.1',
          title: 'The Token Economy: How AI Billing Actually Works',
          duration: '10 min',
          type: 'video',
          preview: "Most people have no idea they're paying per token. Input tokens, output tokens, cached tokens — it's like understanding your phone bill for the first time.",
          content: [
            'Input tokens vs output tokens pricing',
            'How different models charge differently',
            "The real cost of a 'free' conversation",
            'Reading your API usage dashboard',
            'Hands-on: Calculate cost of 20 real prompts',
          ],
        },
        {
          id: '2.6.2',
          title: 'Token Counting Like a Pro',
          duration: '8 min',
          type: 'video',
          preview: "1 token ≈ 0.75 words in English. But emojis, code, and other languages tokenize differently. Master token counting and you'll predict costs before hitting send.",
          content: [
            'The word-to-token conversion rules',
            'Special characters and their token costs',
            'Code vs prose token differences',
            'Multi-language token considerations',
            'Hands-on: Token counting speed challenge',
          ],
        },
        {
          id: '2.6.3',
          title: 'Context Windows: Your Token Budget',
          duration: '10 min',
          type: 'video',
          preview: "Every AI has a 'memory limit' measured in tokens. Claude can handle 200K tokens, ChatGPT varies by model. Understanding this changes how you structure conversations.",
          content: [
            'What context windows actually mean',
            'How conversations eat up your window',
            'When to start fresh vs continue',
            'Model comparison: context window sizes',
            'Hands-on: Manage a conversation within budget',
          ],
        },
        {
          id: '2.6.4',
          title: 'Token Audit Lab: Find Your Waste',
          duration: '15 min',
          type: 'lab',
          preview: "Take your last 10 AI conversations and audit them for token waste. Most people discover they're wasting 40-60% of their tokens on unnecessary fluff.",
          content: [
            'Export your conversation history',
            'The token waste audit checklist',
            'Identify the 5 biggest token wasters',
            'Calculate your monthly AI spend',
            'Lab: Create your token budget plan',
          ],
        },
      ],
    },
    {
      week: 7,
      title: 'Token-Saving Strategies',
      lessons: [
        {
          id: '2.7.1',
          title: 'The 7 Token-Saving Commandments',
          duration: '12 min',
          type: 'video',
          preview: 'Cut your AI costs by 50% with these 7 rules: be concise, skip pleasantries, use structured prompts, limit output length, choose the right model, batch tasks, and cache responses.',
          content: [
            'Commandment 1: Kill the fluff',
            "Commandment 2: Skip 'please' and 'thank you'",
            'Commandment 3: Use structured prompts',
            'Commandment 4: Limit output with constraints',
            'Commandment 5-7: Model selection, batching, caching',
          ],
        },
        {
          id: '2.7.2',
          title: 'Prompt Compression: Same Quality, Half the Tokens',
          duration: '10 min',
          type: 'video',
          preview: "Learn to compress a 200-token prompt into 80 tokens without losing quality. It's like packing a suitcase — everything important fits, nothing unnecessary makes the trip.",
          content: [
            'The compression ratio technique',
            'Before/after: 10 compressed prompts',
            'What to cut vs what to keep',
            'Compression for different task types',
            'Hands-on: Compress your 10 most-used prompts',
          ],
        },
        {
          id: '2.7.3',
          title: 'Model Selection: Stop Using a Ferrari for Groceries',
          duration: '10 min',
          type: 'video',
          preview: 'Using GPT-4 for simple tasks is like driving a Ferrari to buy milk. Learn which model fits which task — your wallet will thank you.',
          content: [
            'Model tiers: when to use what',
            'Cost comparison across models',
            "The 'good enough' principle",
            'Routing tasks to the right model',
            'Hands-on: Re-route 10 tasks to optimal models',
          ],
        },
        {
          id: '2.7.4',
          title: 'Token Saving Challenge: The $1 Day',
          duration: '20 min',
          type: 'lab',
          preview: 'Can you complete a full day of AI-assisted work spending only $1 in tokens? This challenge teaches you to be strategic about every single prompt.',
          content: [
            'The $1 budget challenge rules',
            'Strategy planning before prompting',
            'Token tracking throughout the day',
            'Cost-per-output analysis',
            'Lab: Complete 10 real tasks under $1 total',
          ],
        },
      ],
    },
    {
      week: 8,
      title: 'Prompt Chaining & Workflows',
      lessons: [
        {
          id: '2.8.1',
          title: 'Prompt Chaining: Multi-Step AI Workflows',
          duration: '12 min',
          type: 'video',
          preview: 'One prompt rarely gets you to the finish line. Chaining is like an assembly line — each prompt handles one step, feeding its output into the next prompt.',
          content: [
            'What is prompt chaining?',
            'The assembly line analogy',
            'Designing your chain: input → process → output',
            'When to chain vs when to use one prompt',
            'Hands-on: Build your first 3-step chain',
          ],
        },
        {
          id: '2.8.2',
          title: 'Chaining for Content Creation Pipeline',
          duration: '10 min',
          type: 'video',
          preview: 'Build a content factory: Prompt 1 generates ideas → Prompt 2 creates outlines → Prompt 3 writes drafts → Prompt 4 edits and polishes. Automate your entire writing workflow.',
          content: [
            'The 4-step content pipeline',
            'Research → Outline → Draft → Edit chain',
            'Token-efficient handoffs between steps',
            'Quality checkpoints in chains',
            'Hands-on: Build your content creation pipeline',
          ],
        },
        {
          id: '2.8.3',
          title: 'Chaining for Data Analysis & Decisions',
          duration: '10 min',
          type: 'video',
          preview: 'Feed AI raw data → get it summarized → analyze patterns → generate recommendations → format for stakeholders. A 5-minute chain that replaces hours of manual analysis.',
          content: [
            'The analysis chain pattern',
            'Data → Summary → Insights → Actions',
            'Handling large datasets in chains',
            'Token-efficient data processing',
            'Hands-on: Analyze a real dataset with chaining',
          ],
        },
        {
          id: '2.8.4',
          title: 'Month 2 Capstone: Token-Optimized Workflow',
          duration: '25 min',
          type: 'project',
          preview: 'Build a complete AI workflow that solves a real business problem while spending minimum tokens. Compare your optimized version against a naive approach and measure the savings.',
          content: [
            'Choose a complex business problem',
            'Build the naive (expensive) solution first',
            'Optimize for token efficiency',
            'Measure: quality maintained, cost reduced',
            'Submit with token savings report',
          ],
        },
      ],
    },
  ],
};
