export const MONTH_1 = {
  id: 1,
  title: 'Foundations',
  color: '#10B981',
  icon: '🌱',
  quizAfter: 'quiz1',
  quizTitle: 'Fun Quiz #1: Prompt Foundations Showdown',
  weeks: [
    {
      week: 1,
      title: 'Understanding AI & Large Language Models',
      lessons: [
        {
          id: '1.1.1',
          title: 'What is AI, Really? (No Jargon Edition)',
          duration: '8 min',
          type: 'video',
          preview: "Think of AI like a super-smart autocomplete that read the entire internet. In this lesson, you'll understand what AI actually does behind the scenes — no PhD required.",
          content: [
            'AI is pattern recognition at massive scale',
            'How LLMs predict the next word',
            "Why AI sometimes 'hallucinates'",
            'The difference between AI, ML, and LLMs',
            'Hands-on: Your first conversation with Claude',
          ],
        },
        {
          id: '1.1.2',
          title: 'How ChatGPT, Claude & Gemini Actually Work',
          duration: '10 min',
          type: 'video',
          preview: "Ever wondered why different AI tools give different answers? It's like asking three different experts the same question — each has different training and personality.",
          content: [
            'Training data and knowledge cutoffs',
            'Why Claude ≠ ChatGPT ≠ Gemini',
            'Context windows explained simply',
            "What 'tokens' are (your new currency)",
            'Hands-on: Compare responses across 3 AI tools',
          ],
        },
        {
          id: '1.1.3',
          title: "What Are Tokens & Why You're Burning Money",
          duration: '12 min',
          type: 'video',
          preview: "Every word you type costs money. 'Hello' = 1 token. A rambling prompt? Maybe 500 tokens. Learn to think in tokens and you'll save 40-60% on AI costs.",
          content: [
            'Tokens = pieces of words (not whole words)',
            'How pricing works: input vs output tokens',
            'The token counter exercise',
            "Why 'please' and 'thank you' cost real money",
            'Hands-on: Calculate the cost of 10 different prompts',
          ],
        },
        {
          id: '1.1.4',
          title: 'Setting Up Your AI Toolkit',
          duration: '15 min',
          type: 'lab',
          preview: "Time to get your hands dirty! We'll set up free accounts on Claude, ChatGPT, and a token counter tool. By the end, you'll have your prompt engineering lab ready.",
          content: [
            'Create accounts on Claude.ai and ChatGPT',
            'Install the Tokenizer browser extension',
            'Set up your Prompt Journal (Google Doc template)',
            'Your first 5-prompt challenge',
            'Lab: Build your personal AI workspace',
          ],
        },
      ],
    },
    {
      week: 2,
      title: 'Anatomy of a Perfect Prompt',
      lessons: [
        {
          id: '1.2.1',
          title: "Why 90% of Prompts Fail (And Yours Won't)",
          duration: '8 min',
          type: 'video',
          preview: "Most people type 'write me a blog post' and wonder why the result is generic. It's like ordering 'food' at a restaurant — you'll get something, but probably not what you wanted.",
          content: [
            'The 5 deadly sins of bad prompts',
            'Vague vs specific: side-by-side comparison',
            "The 'restaurant order' framework",
            "Why AI can't read your mind (yet)",
            'Hands-on: Fix 5 terrible prompts',
          ],
        },
        {
          id: '1.2.2',
          title: 'The R-T-F Framework: Role, Task, Format',
          duration: '10 min',
          type: 'video',
          preview: "The RTF framework is your secret weapon. Tell AI WHO it is, WHAT to do, and HOW to format it. Master this and you'll outperform 95% of AI users instantly.",
          content: [
            "Role: Setting the AI's expertise level",
            'Task: Being specific about what you want',
            'Format: Controlling the output structure',
            '12 RTF templates for common tasks',
            'Hands-on: Write 5 RTF prompts for your job',
          ],
        },
        {
          id: '1.2.3',
          title: 'Context is King: Feeding AI the Right Info',
          duration: '10 min',
          type: 'video',
          preview: "Imagine hiring a consultant but telling them nothing about your company. That's what you do when you prompt without context. Let's fix that.",
          content: [
            'What context to include (and what to skip)',
            "The 'briefing document' technique",
            'How much context is too much?',
            'Context vs instructions vs examples',
            'Hands-on: Create a context template for your work',
          ],
        },
        {
          id: '1.2.4',
          title: 'Constraints & Guardrails: Controlling AI Output',
          duration: '12 min',
          type: 'lab',
          preview: 'Without constraints, AI will write you a 2000-word essay when you wanted 3 bullet points. Learn to put guardrails on your AI like a pro.',
          content: [
            'Word/character limits that actually work',
            'Tone and style constraints',
            "Negative prompting: 'Do NOT...'",
            'Output format enforcement',
            'Lab: Build a constraint library for 10 use cases',
          ],
        },
      ],
    },
    {
      week: 3,
      title: 'Core Prompting Techniques',
      lessons: [
        {
          id: '1.3.1',
          title: 'Zero-Shot Prompting: Ask Once, Get It Right',
          duration: '8 min',
          type: 'video',
          preview: "Zero-shot means giving AI a task with no examples — just pure instruction. It's the fastest technique but requires precision. Think of it as giving perfect directions to a taxi driver in a foreign city.",
          content: [
            'What zero-shot actually means',
            'When to use it (and when NOT to)',
            'The precision formula for zero-shot',
            '10 zero-shot templates that work every time',
            'Hands-on: Master the one-shot prompt',
          ],
        },
        {
          id: '1.3.2',
          title: "Few-Shot Prompting: Show, Don't Tell",
          duration: '10 min',
          type: 'video',
          preview: "Instead of explaining what you want, SHOW the AI examples. It's like training a new employee — give them 2-3 samples of great work and say 'do it like this.'",
          content: [
            'The power of examples in prompts',
            'How many examples? The 2-3 sweet spot',
            'Choosing the RIGHT examples',
            'Few-shot for different output types',
            'Hands-on: Convert 5 zero-shot prompts to few-shot',
          ],
        },
        {
          id: '1.3.3',
          title: 'Chain-of-Thought: Make AI Think Step by Step',
          duration: '12 min',
          type: 'video',
          preview: "Adding 'think step by step' to your prompt can improve accuracy by 40%. It forces AI to show its work, like a math teacher who won't accept answers without the process.",
          content: [
            "Why 'think step by step' is magic",
            'Chain-of-thought for analysis tasks',
            'Chain-of-thought for decision making',
            'When CoT wastes tokens (and money)',
            'Hands-on: Solve 5 complex problems with CoT',
          ],
        },
        {
          id: '1.3.4',
          title: 'Technique Showdown: Which Method When?',
          duration: '15 min',
          type: 'lab',
          preview: 'Now that you know three techniques, when do you use which? This lab has you solve the same problem three ways and compare results, quality, and token cost.',
          content: [
            'Decision matrix: technique vs task type',
            'Speed vs quality vs cost tradeoffs',
            'Combining techniques for power prompts',
            'The technique selection flowchart',
            'Lab: Solve 5 challenges using the optimal technique',
          ],
        },
      ],
    },
    {
      week: 4,
      title: 'Prompt Frameworks & Templates',
      lessons: [
        {
          id: '1.4.1',
          title: 'The CRISP Framework for Business Prompts',
          duration: '10 min',
          type: 'video',
          preview: 'CRISP = Context, Role, Instructions, Style, Parameters. This framework turns any business request into a prompt that gets boardroom-quality output.',
          content: [
            'C - Context: Business background',
            'R - Role: Expert persona',
            'I - Instructions: Clear directives',
            'S - Style: Tone and voice',
            'P - Parameters: Constraints and format',
          ],
        },
        {
          id: '1.4.2',
          title: 'Building Your Personal Prompt Library',
          duration: '12 min',
          type: 'video',
          preview: "Stop rewriting prompts from scratch every time. Build a reusable library of your best prompts, organized by task. It's like having a recipe book for AI.",
          content: [
            'Organizing prompts by category',
            'Template variables: [TOPIC], [AUDIENCE], etc.',
            'Version control for prompts',
            'Sharing prompts with your team',
            'Hands-on: Create your 20-prompt starter library',
          ],
        },
        {
          id: '1.4.3',
          title: 'Prompts for Every Job: 50 Ready-to-Use Templates',
          duration: '15 min',
          type: 'resource',
          preview: "Marketing, HR, teaching, sales, writing, analysis, coding — we've got 50 battle-tested templates organized by profession. Copy, customize, and deploy.",
          content: [
            '10 Marketing & Content prompts',
            '10 Business & Analysis prompts',
            '10 Education & Training prompts',
            '10 Writing & Creative prompts',
            '10 Personal Productivity prompts',
          ],
        },
        {
          id: '1.4.4',
          title: 'Month 1 Capstone: Your First AI Workflow',
          duration: '20 min',
          type: 'project',
          preview: 'Time to put it all together! Build a 3-step AI workflow that solves a real problem from your work or life. This becomes the first piece of your portfolio.',
          content: [
            'Choose your real-world problem',
            'Design a 3-step prompt chain',
            'Measure token usage and cost',
            'Document your workflow',
            'Submit for peer review',
          ],
        },
      ],
    },
  ],
};
