export const MONTH_3 = {
  id: 3,
  title: 'Professional & Certification',
  color: '#F59E0B',
  icon: '🏆',
  quizAfter: null,
  weeks: [
    {
      week: 9,
      title: 'Industry-Specific Prompting',
      lessons: [
        {
          id: '3.9.1',
          title: 'Prompting for Marketing & Content Teams',
          duration: '12 min',
          type: 'video',
          preview: 'SEO blog posts, social media calendars, ad copy, email campaigns — every marketing task has an optimal prompt pattern. Learn the templates the top agencies use.',
          content: [
            'Blog post generation prompts',
            'Social media content calendars',
            'Ad copy A/B testing with AI',
            'Email sequence generation',
            "Hands-on: Create a week's content in 30 minutes",
          ],
        },
        {
          id: '3.9.2',
          title: 'Prompting for Business & Operations',
          duration: '12 min',
          type: 'video',
          preview: 'Meeting summaries, SOPs, market analysis, competitor research, financial modeling — AI can handle the grunt work if you know how to ask.',
          content: [
            'Meeting notes → action items pipeline',
            'SOP generation and formatting',
            'Competitor analysis frameworks',
            'Financial data interpretation',
            'Hands-on: Automate 3 business workflows',
          ],
        },
        {
          id: '3.9.3',
          title: 'Prompting for Education & Training',
          duration: '10 min',
          type: 'video',
          preview: "Lesson plans, quiz generation, study guides, personalized learning paths — if you're a teacher or trainer, these prompts will save you 10+ hours a week.",
          content: [
            'Lesson plan generation',
            'Quiz and assessment creation',
            'Adaptive learning path design',
            'Student feedback and grading assistance',
            'Hands-on: Create a complete lesson plan with AI',
          ],
        },
        {
          id: '3.9.4',
          title: 'Industry Prompt Sprint',
          duration: '20 min',
          type: 'lab',
          preview: 'Pick your industry, solve 5 real problems using optimized prompts, measure token usage, and add the best prompts to your professional library.',
          content: [
            'Select your industry track',
            'Solve 5 industry-specific challenges',
            'Optimize each prompt for tokens',
            'Peer review with same-industry peers',
            'Lab: Build your industry prompt library',
          ],
        },
      ],
    },
    {
      week: 10,
      title: 'APIs & Building AI Tools',
      lessons: [
        {
          id: '3.10.1',
          title: 'APIs for Dummies: The Restaurant Analogy',
          duration: '10 min',
          type: 'video',
          preview: "An API is just a waiter. You give an order (request) to the waiter (API) who takes it to the kitchen (AI model) and brings back your food (response). That's it!",
          content: [
            'The restaurant analogy in depth',
            'Request → Processing → Response flow',
            'API keys = your restaurant membership card',
            'Rate limits = kitchen capacity',
            'Hands-on: Make your first API call (no coding!)',
          ],
        },
        {
          id: '3.10.2',
          title: 'No-Code AI Tools: Zapier, Make & Friends',
          duration: '12 min',
          type: 'video',
          preview: "You don't need to code to build AI tools. Zapier and Make let you connect AI to email, spreadsheets, calendars, and 5000+ apps with drag-and-drop.",
          content: [
            'Zapier + AI: automated workflows',
            'Make.com: visual AI pipelines',
            'Connecting AI to Google Sheets',
            'Automated email responses with AI',
            'Hands-on: Build a no-code AI automation',
          ],
        },
        {
          id: '3.10.3',
          title: 'Building Simple AI Apps with Cursor/Bolt',
          duration: '15 min',
          type: 'video',
          preview: "AI-powered IDEs like Cursor and Bolt let you build websites and apps by describing what you want in plain English. It's like having a developer who works for free.",
          content: [
            'What are AI-powered IDEs?',
            'Cursor: describe → build → deploy',
            'Bolt.new: instant web apps',
            'Prompting for code generation',
            'Hands-on: Build a simple web app in 20 minutes',
          ],
        },
        {
          id: '3.10.4',
          title: 'AI Tool Builder Lab',
          duration: '25 min',
          type: 'lab',
          preview: 'Build a real, working AI-powered tool — a chatbot, a content generator, or an automation — using no-code platforms. This goes straight into your portfolio.',
          content: [
            'Choose your tool type',
            'Design the user flow',
            'Build with no-code platform',
            'Test and iterate',
            'Lab: Deploy your first AI tool',
          ],
        },
      ],
    },
    {
      week: 11,
      title: 'AI in Daily Life & Career Strategy',
      lessons: [
        {
          id: '3.11.1',
          title: 'Your AI-Powered Morning Routine',
          duration: '8 min',
          type: 'video',
          preview: "From summarizing overnight emails to planning your day to generating your to-do list — here's how to start every morning with AI doing the heavy lifting.",
          content: [
            'Morning email triage with AI',
            'AI-powered daily planning',
            'News summarization workflow',
            'Priority setting with AI analysis',
            'Hands-on: Design your AI morning routine',
          ],
        },
        {
          id: '3.11.2',
          title: 'Job Hunting with AI: The Unfair Advantage',
          duration: '12 min',
          type: 'video',
          preview: 'AI-optimized resumes get 3x more callbacks. Learn to use AI for resume tailoring, cover letter generation, interview prep, and salary negotiation scripts.',
          content: [
            'Resume optimization with AI',
            'Cover letter generation per job posting',
            'Interview question preparation',
            'Salary negotiation scripts',
            'Hands-on: Optimize your resume with AI',
          ],
        },
        {
          id: '3.11.3',
          title: 'Freelancing as a Prompt Engineer',
          duration: '10 min',
          type: 'video',
          preview: 'Prompt engineers earn $50-150/hour on platforms like Upwork and Fiverr. Learn how to position yourself, price your services, and land your first client.',
          content: [
            'The prompt engineering job market',
            'Building your service offerings',
            'Pricing strategies for beginners',
            'Portfolio creation and presentation',
            'Hands-on: Create your freelancer profile',
          ],
        },
        {
          id: '3.11.4',
          title: 'Portfolio & Personal Brand Lab',
          duration: '20 min',
          type: 'lab',
          preview: 'Build your professional portfolio showcasing 10+ prompt engineering projects. Create your LinkedIn presence as a Certified Prompt Engineer.',
          content: [
            'Curate your best 10 projects',
            'Write case studies for top 3',
            'Design your portfolio page',
            'Optimize your LinkedIn profile',
            'Lab: Launch your professional presence',
          ],
        },
      ],
    },
    {
      week: 12,
      title: 'Review & Certification',
      lessons: [
        {
          id: '3.12.1',
          title: 'Comprehensive Review: Foundations',
          duration: '15 min',
          type: 'review',
          preview: 'A rapid-fire review of everything from Month 1 — prompt anatomy, RTF framework, zero-shot, few-shot, chain-of-thought, and your prompt library.',
          content: [
            'Quick recap: AI & LLM basics',
            'Review: Prompt anatomy & RTF',
            'Review: Core techniques',
            'Review: Frameworks & templates',
            'Practice: 20 rapid-fire prompt challenges',
          ],
        },
        {
          id: '3.12.2',
          title: 'Comprehensive Review: Token Mastery',
          duration: '15 min',
          type: 'review',
          preview: 'Review all token-saving strategies, prompt compression techniques, model selection rules, and workflow optimization patterns from Month 2.',
          content: [
            'Review: Token economics',
            'Review: 7 commandments of token saving',
            'Review: Prompt compression',
            'Review: Model selection & chaining',
            'Practice: Optimize 10 expensive prompts',
          ],
        },
        {
          id: '3.12.3',
          title: 'Comprehensive Review: Professional Skills',
          duration: '15 min',
          type: 'review',
          preview: "Review industry prompting, API basics, no-code tools, and career strategy. Make sure you're ready for the certification exam.",
          content: [
            'Review: Industry-specific prompting',
            'Review: APIs and no-code tools',
            'Review: Career strategy',
            'Review: Portfolio and personal brand',
            'Practice: Mock certification questions',
          ],
        },
        {
          id: '3.12.4',
          title: 'Certification Exam',
          duration: '60 min',
          type: 'exam',
          preview: "This is it! 50 questions covering all 12 weeks. Score 89%+ and you earn your Certified Prompt Engineer badge + Job Guarantee. You've got this!",
          content: [
            'Part 1: Multiple Choice (30 questions)',
            'Part 2: Prompt Analysis (10 questions)',
            'Part 3: Practical Application (10 questions)',
            'Passing score: 70% | Job Guarantee: 89%+',
            'Certificate issued within 24 hours',
          ],
        },
      ],
    },
  ],
};
